xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.6742064356803894
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 42.280372619628906
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 230.8286590576172
    PRES_surface:
      dims: []
      attrs: {}
      data: 716.4165649414062
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.0027736087795346975
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 6.741388320922852
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.9892613887786865
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 2.5411665439605713
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    APCP_surface:
      dims: []
      attrs: {}
      data: 0.21463747322559357
    DLWRF_surface:
      dims: []
      attrs: {}
      data: 312.11492919921875
    DSWRF_surface:
      dims: []
      attrs: {}
      data: 157.4867401123047
    PRES_surface:
      dims: []
      attrs: {}
      data: 101555.296875
    SPFH_2maboveground:
      dims: []
      attrs: {}
      data: 0.006856684107333422
    TMP_2maboveground:
      dims: []
      attrs: {}
      data: 283.443115234375
    UGRD_10maboveground:
      dims: []
      attrs: {}
      data: 1.110012412071228
    VGRD_10maboveground:
      dims: []
      attrs: {}
      data: 1.1845113039016724
